### ISSUE TITLE
"Range:": make it a template

### ISSUE THREAD

**Issue by Nickduino** [Springvar/home-assistant-flightradar24-card#10]
I'd like to change the string (i.e. translate it) for "Range:" on the top left corner: 

![image](https://github.com/user-attachments/assets/abbdb89b-91d4-4f90-933f-fb46cc0997bf)

Being able to add a space between the value and the unit would be cool too

Would it be possible to add it to the templates?

Or make it a basic configuration like the `no_flights_message`?

**Comment by Springvar** [comment]
A radar_range template is added in v0.0.11-pre.2

Please check and verify that it does what you need.

**Comment by Nickduino** [comment]
> Please check and verify that it does what you need.

![image](https://github.com/user-attachments/assets/38e25828-cf77-444e-9222-7dbc319ff3f6)
