### ISSUE TITLE
FR: set the range 'rings'

### ISSUE THREAD

**Issue by RedNo7** [Springvar/home-assistant-flightradar24-card#2]
Hi,

I already posted this on your [homeassistant forum thread](https://community.home-assistant.io/t/flightradar24-card/739024/9?u=jchh) , but thought it better to add a feature request here.

Would it be possible to set the radius interval for the range 'rings' (not sure of the correct term for them) which are currently set at 10km?  For example, I am interested in a 10km range, with concentric circles at 2km intervals.

**Comment by Springvar** [comment]
v0.0.9 includes a new configuration option for the ring distance

**Comment by RedNo7** [comment]
Thank you!
