### ISSUE TITLE
flightradar24 card is not selectable as a new card

### ISSUE THREAD

**Issue by PV-Joe** [Springvar/home-assistant-flightradar24-card#3]
Hello,

I've installed successfully from HACS and restarted.
I can't select the card as a new card as it doesn't appear.

Is this a bug or am I missing another step to finally install?

Help is much appreciated.

**Comment by DoverKan** [comment]
The same thing happens to me

**Comment by Springvar** [comment]
The card must be configured as a custom card.
Ref: https://github.com/Springvar/home-assistant-flightradar24-card?tab=readme-ov-file#configuration
