### ISSUE TITLE
Zoom-out and max range

### ISSUE THREAD

**Issue by Nickduino** [Springvar/home-assistant-flightradar24-card#8]
I like the fact you can use the scroll-wheel to zoom-in and zoom-out but the zoom-out seems to hit a hard stop at 100 km (while it's possible to define a default range **higher** than this and is will display properly as long as you don't scroll).

Could you consider removing the hard stop at 100 km?

It would also be realllllly nice to be able to move (pan) the radar North/South/East/West

**Comment by Springvar** [comment]
There is an undocumented max_range setting for radar which can be used to increase the hard stop value. I'll make sure to add it to the README for an upcoming release.

**Comment by Nickduino** [comment]
> There is an undocumented max_range setting for radar

Great, I did that.


> I'll make sure to add it to the README for an upcoming release.

...and make sure max_range is set to (at least) the value of range when range is over 100.




Also, could the zooming be a relative value of the currant range displayed instead of a relative value? 5 km is fine when your range is 20 km but when it's 500 km, it gets boring pretty fast.
